name: 'Deploy Cloud Commerce to Firebase'
description: 'A GitHub Action to deploy https://github.com/ecomplus/cloud-commerce store to Firebase'

inputs:
  github-token:
    description: 'The `GITHUB_TOKEN` secret'
    required: true
  firebase-service-account:
    description: 'Firebase service account JSON'
    required: true
  ecom-authentication-id:
    description: 'E-Com Plus store authentication ID'
    required: true
  ecom-api-key:
    description: 'E-Com Plus store API key'
    required: true
  ecom-store-id:
    description: 'Store ID if not defined in config.json'
  tiny-erp-token:
    description: 'App: Tiny ERP API token'
  mail-sender:
    description: "Emails: sender email"
  mail-sender-name:
    description: "Emails: sender name (default is store name)"
  mail-reply-to:
    description: "Emails: Reply email"
  smpt-host: 
    description: "Emails": SMTP hostname"
  smpt-port: 
    description: "Emails": SMTP port number"
  smpt-user: 
    description: "Emails": SMTP username"
  smpt-pass: 
    description: "Emails": SMTP password"
  sendgrid-api-key:
    description: 'Emails: SendGrid API key configuration'

outputs: {}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - if: github.event_name == 'push'
      shell: bash
      run: npm i --location=global firebase-tools@11

    - shell: bash
      run: npm ci --omit=dev

    - shell: bash
      working-directory: functions
      env:
        ECOM_STORE_ID: ${{ inputs.ecom-store-id }}
      run: |
        for d in */ ; do
          cd $d
          npm ci
          cd ..
        done
        echo "ecom_store_id=${ECOM_STORE_ID:-$(cat config.json | jq -r '.storeId')}" >> $GITHUB_ENV

    - if: github.event_name == 'push'
      name: Deploy to Firebase live
      shell: bash
      env:
        ECOM_STORE_ID: ${{ env.ecom_store_id }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        FIREBASE_SERVICE_ACCOUNT: ${{ inputs.firebase-service-account }}
        ECOM_AUTHENTICATION_ID: ${{ inputs.ecom-authentication-id }}
        ECOM_API_KEY: ${{ inputs.ecom-api-key }}
        TINY_ERP_TOKEN: ${{ inputs.tiny-erp-token }}
        MAIL_SENDER: ${{ inputs.mail-sender }}
        MAIL_SENDER_NAME: ${{ inputs.mail-sender-name }}
        MAIL_REPLY_TO: ${{ inputs.mail-reply-to }}
        SMTP_HOST: ${{ inputs.smpt-host }}
        SMTP_PORT: ${{ inputs.smpt-port }}
        SMTP_USER: ${{ inputs.smpt-user }}
        SMTP_PASS: ${{ inputs.smpt-pass }}
        SENDGRID_API_KEY: ${{ inputs.sendgrid-api-key }}

      run: |
        export GAC_FILENAME=".gac-$RANDOM.json"
        echo $FIREBASE_SERVICE_ACCOUNT > $GAC_FILENAME
        printf "DEPLOY_RAND=$RANDOM.$RANDOM
        ECOM_AUTHENTICATION_ID=$ECOM_AUTHENTICATION_ID
        ECOM_API_KEY=$ECOM_API_KEY
        ECOM_STORE_ID=$ECOM_STORE_ID
        GITHUB_TOKEN=$GITHUB_TOKEN
        TINY_ERP_TOKEN=$TINY_ERP_TOKEN
        MAIL_SENDER=$MAIL_SENDER
        MAIL_SENDER_NAME=$MAIL_SENDER_NAME
        MAIL_REPLY_TO=$MAIL_REPLY_TO
        SMTP_HOST=$SMTP_HOST
        SMTP_PORT=$SMTP_PORT
        SMTP_USER=$SMTP_USER
        SMTP_PASS=$SMTP_PASS
        SENDGRID_API_KEY=$SENDGRID_API_KEY
        " > functions/.env
        GOOGLE_APPLICATION_CREDENTIALS=$GAC_FILENAME npm run deploy

    - if: github.event_name == 'pull_request'
      shell: bash
      env:
        ECOM_STORE_ID: ${{ env.ecom_store_id }}
      run: |
        printf "DEPLOY_RAND=$RANDOM.$RANDOM
        ECOM_STORE_ID=$ECOM_STORE_ID
        " > functions/ssr/.env
        if [ ! -f ".firebaserc" ]; then
          echo '{ "projects": { "default": "ecom2-002" } }' > .firebaserc
        fi
        npm --prefix "functions/ssr/" run build:static && npm run build -- --codebase ssr

    - if: github.event_name == 'pull_request'
      name: Deploy Firebase Hosting PR preview
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ inputs.github-token }}
        firebaseServiceAccount: ${{ inputs.firebase-service-account }}
