name: 'Deploy Cloud Commerce to Firebase'
description: 'A GitHub Action to deploy https://github.com/ecomplus/cloud-commerce store to Firebase'

inputs:
  github-token:
    description: 'The `GITHUB_TOKEN` secret'
    required: true
  firebase-service-account:
    description: 'Firebase service account JSON'
    required: true
  ecom-authentication-id:
    description: 'E-Com Plus store authentication ID'
    required: true
  ecom-api-key:
    description: 'E-Com Plus store API key'
    required: true
  ecom-store-id:
    description: 'Store ID if not defined in config.json'
  tiny-erp-token:
    description: 'App: Tiny ERP API token'

outputs: {}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - if: github.event_name == 'push'
      shell: bash
      run: npm i --location=global firebase-tools@11

    - shell: bash
      run: npm ci --omit=dev

    - shell: bash
      working-directory: functions
      run: |
        for d in */ ; do
          cd $d
          npm ci
          cd ..
        done

    - if: github.event_name == 'push'
      name: Deploy to Firebase live
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        FIREBASE_SERVICE_ACCOUNT: ${{ inputs.firebase-service-account }}
        ECOM_AUTHENTICATION_ID: ${{ inputs.ecom-authentication-id }}
        ECOM_API_KEY: ${{ inputs.ecom-api-key }}
        ECOM_STORE_ID: ${{ inputs.ecom-store-id }}
        TINY_ERP_TOKEN: ${{ inputs.tiny-erp-token }}
      run: |
        export GAC_FILENAME=".gac-$RANDOM.json"
        echo $FIREBASE_SERVICE_ACCOUNT > $GAC_FILENAME
        printf "ECOM_AUTHENTICATION_ID=$ECOM_AUTHENTICATION_ID
        ECOM_API_KEY=$ECOM_API_KEY
        ECOM_STORE_ID=$ECOM_STORE_ID
        GITHUB_TOKEN=$GITHUB_TOKEN
        TINY_ERP_TOKEN=$TINY_ERP_TOKEN
        DEPLOY_RAND=$RANDOM.$RANDOM
        " > functions/.env
        GOOGLE_APPLICATION_CREDENTIALS=$GAC_FILENAME npm run deploy
    
    - if: github.event_name == 'pull_request'
      shell: bash
      working-directory: functions/ssr
      run: npm run build:static

    - if: github.event_name == 'pull_request'
      name: Deploy Firebase Hosting PR preview
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ inputs.github-token }}
        firebaseServiceAccount: ${{ inputs.firebase-service-account }}
