packages:
  - 'packages/*'
  - 'packages/apps/*'
  - 'docs'
  - 'store'
  - 'store/functions/*'
  - 'ecomplus-stores/barradoce'
  - 'ecomplus-stores/barradoce/functions/*'
  - 'ecomplus-stores/tiasonia'
  - 'ecomplus-stores/tiasonia/functions/*'
