minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@ecomplus/*'
  - '@cloudcommerce/*'
  # Renovate security update: fast-xml-parser@5.3.4
  - fast-xml-parser@5.3.4
packages:
  - 'packages/*'
  - 'packages/apps/*'
  - 'docs'
  - 'store'
  - 'store/functions/*'
  - 'ecomplus-stores/*'
  - 'ecomplus-stores/*/functions/*'
