packages:
  - 'packages/*'
  - 'packages/apps/*'
  - 'docs'
  - 'store'
  - 'store/*'
  - 'store/functions/*'
  - 'ecomplus-stores/monocard'
  - 'ecomplus-stores/monocard/*'
  - 'ecomplus-stores/monocard/functions/*'
