minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@ecomplus/*'
  - '@cloudcommerce/*'
  # Renovate security update: axios@1.13.5
  - axios@1.13.5
  # Renovate security update: qs@6.14.2
  - qs@6.14.2
packages:
  - 'packages/*'
  - 'packages/apps/*'
  - 'docs'
  - 'store'
  - 'store/functions/*'
  - 'ecomplus-stores/*'
  - 'ecomplus-stores/*/functions/*'
