minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@ecomplus/*'
  - '@cloudcommerce/*'
packages:
  - 'packages/*'
  - 'packages/apps/*'
  - 'docs'
  - 'store'
  - 'store/functions/*'
  - 'ecomplus-stores/*'
  - 'ecomplus-stores/*/functions/*'
