packages:
  - 'packages/*'
  - 'packages/apps/*'
  - 'docs'
  - 'store'
  - 'store/functions/*'
  - 'ecomplus-stores/iluminim'
  - 'ecomplus-stores/iluminim/functions/*'
  - 'ecomplus-stores/barra-doce'
  - 'ecomplus-stores/barra-doce/functions/*'
