/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Response - Triggered to validate and apply discount value, must return discount and conditions
 */
export interface ApplyDiscountResponse {
  /**
   * Available but not yet applied discount campaign
   */
  available_extra_discount?: {
    /**
     * Minimum amount to apply the discount
     */
    min_amount?: number;
    /**
     * Name of discount campaign
     */
    label?: string;
    /**
     * Discount type
     */
    type?: 'percentage' | 'fixed';
    /**
     * Discount value, percentage or fixed
     */
    value: number;
  };
  /**
   * Matched discount rule for current UTM campaign or coupon
   */
  discount_rule?: {
    /**
     * Name of the discount rule, can be the coupon or campaign name
     */
    label?: string;
    /**
     * Additional text description for the discount rule
     */
    description?: string;
    /**
     * Extra discount to apply on checkout
     */
    extra_discount: {
      /**
       * Extra discount value
       */
      value: number;
      /**
       * Flags to associate additional info
       *
       * @maxItems 10
       */
      flags?: string[];
    };
  };
  /**
   * Short message for curtomer if coupon/campaign tried is invalid
   */
  invalid_coupon_message?: string;
  /**
   * List of available freebie (gift) products
   *
   * @maxItems 3000
   */
  freebie_product_ids?: string[];
}
