/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Product object model
 */
export interface Products {
  /**
   * Product ID (ObjectID) [auto]
   */
  _id: string & { length: 24 };
  /**
   * When object was seted (POST/PUT), date and time in ISO 8601 standard representation [auto]
   */
  created_at: string;
  /**
   * When was it last changed, date and time in ISO 8601 standard representation [auto]
   */
  updated_at: string;
  /**
   * ID of store [auto]
   */
  store_id: number;
  /**
   * List of sales channels if product not available in all channels
   *
   * @maxItems 10
   */
  channel_ids?: string[];
  /**
   * Product unique reference code
   */
  sku: string;
  /**
   * Product type
   */
  commodity_type?: 'physical' | 'digital';
  /**
   * Product full name
   */
  name: string;
  /**
   * Slug to complete page URL, starting with number or lowercase letter
   */
  slug?: string;
  /**
   * Status defined by seller, such as draft or live
   */
  status?: string;
  /**
   * True when product is complete registered and ready to sell
   */
  available?: boolean;
  /**
   * Visible on search results, collections and catalogs
   */
  visible?: boolean;
  /**
   * Number to define the importance of the ad, the higher should be displayed first
   */
  ad_relevance?: number;
  /**
   * Short product description in plain text
   */
  short_description?: string;
  /**
   * Full product description, may use HTML tags
   */
  body_html?: string;
  /**
   * Title tag for page SEO
   */
  meta_title?: string;
  /**
   * Meta description tag for page SEO
   */
  meta_description?: string;
  /**
   * Text translations for internationalization
   */
  i18n?: {
    /**
     * Language specific text fields
     *
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-z]{2}(_[a-z]{2})?$".
     */
    [k: string]: {
      /**
       * Product full name
       */
      name?: string;
      /**
       * Short product description in plain text
       */
      short_description?: string;
      /**
       * Full product description, may use HTML tags
       */
      body_html?: string;
      /**
       * Title tag for page SEO
       */
      meta_title?: string;
      /**
       * Meta description tag for page SEO
       */
      meta_description?: string;
    };
  };
  /**
   * Tags related with product for internal search
   *
   * @maxItems 200
   */
  keywords?: string[];
  /**
   * Product sale price, when undefined, product could be bought by any price
   */
  price?: number;
  /**
   * How long sale price is valid, out of this range (if defined), base_price should be applied
   */
  price_effective_date?: {
    /**
     * Start date and time in ISO 8601 standard representation
     */
    start?: string;
    /**
     * Promotion end date and time in ISO 8601 standard representation
     */
    end?: string;
  };
  /**
   * Product original sale price, without discounts
   */
  base_price?: number;
  /**
   * Product cost price to calculate profit
   */
  cost_price?: number;
  /**
   * Designator of currency according to ISO 4217 (3 uppercase letters)
   */
  currency_id?: string;
  /**
   * Graphic symbol used as a shorthand for currency's name
   */
  currency_symbol?: string;
  /**
   * Product quantity available to sell, max to put in cart
   */
  quantity?: number;
  /**
   * Minimum quantity to put in cart
   */
  min_quantity?: number;
  /**
   * Warehouses by code and respective product stock
   */
  inventory?: {
    /**
     * Product quantity available for sale from current warehouse
     *
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[A-Za-z0-9-_]{2,30}$".
     */
    [k: string]: number;
  };
  /**
   * Deadline for production or handling of pre-ordered product
   */
  production_time?: {
    /**
     * Number of days to post the product after purchase, deadline for production or handling
     */
    days: number;
    /**
     * If the deadline is calculated in working days
     */
    working_days?: boolean;
    /**
     * If the production time is cumulative per product unit
     */
    cumulative?: boolean;
    /**
     * When cumulative, increase the term proportionally up to this maximum (in days)
     */
    max_time?: number;
  };
  /**
   * Decrease product available quantity automatically after each order
   */
  manage_stock?: boolean;
  /**
   * Measure and dimension of your product when users might be interested in price per unit
   */
  measurement?: {
    /**
     * Unit of measurement
     */
    unit:
      | 'oz'
      | 'lb'
      | 'mg'
      | 'g'
      | 'kg'
      | 'floz'
      | 'pt'
      | 'qt'
      | 'gal'
      | 'ml'
      | 'cl'
      | 'l'
      | 'cbm'
      | 'in'
      | 'ft'
      | 'yd'
      | 'cm'
      | 'm'
      | 'sqft'
      | 'sqm'
      | 'ct';
    /**
     * Maximum number of decimal places in the product quantity (in unit of measure)
     */
    precision?: number;
    /**
     * Quantity to calculate the price to be shown on ads, such as GMC `unit_pricing_base_measure`
     */
    pricing_base_measure?: number;
  };
  /**
   * Product dimensions with packaging for freight calculation
   */
  dimensions?: {
    /**
     * Package width, height and length
     *
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^width|height|length$".
     */
    [k: string]: {
      /**
       * Size in specified unit
       */
      value: number;
      /**
       * Unit of measurement
       */
      unit?: 'mm' | 'cm' | 'm' | 'ft' | 'in' | 'yd' | 'mi';
    };
  };
  /**
   * Package weight for freight calculation
   */
  weight?: {
    /**
     * Size in specified unit
     */
    value: number;
    /**
     * Unit of measurement
     */
    unit?: 'mg' | 'g' | 'kg' | 'lb' | 'oz';
  };
  /**
   * Item condition
   */
  condition?: 'new' | 'refurbished' | 'used' | 'not_specified';
  /**
   * Product restricted to adults (18+)
   */
  adult?: boolean;
  /**
   * Warranty time and conditions
   */
  warranty?: string;
  /**
   * List of product brands
   *
   * @maxItems 100
   */
  brands?: {
    /**
     * Brand ID (ObjectID)
     */
    _id?: string & { length: 24 };
    /**
     * Brand name
     */
    name: string;
    /**
     * Text translations for internationalization
     */
    i18n?: {
      /**
       * Language specific text fields
       *
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^[a-z]{2}(_[a-z]{2})?$".
       */
      [k: string]: {
        /**
         * Brand name
         */
        name?: string;
      };
    };
    /**
     * Brand page slug
     */
    slug?: string;
    /**
     * Brand logo
     */
    logo?: {
      /**
       * Image link
       */
      url: string;
      /**
       * Image size (width x height) in px, such as 100x50 (100px width, 50px height)
       */
      size?: string;
      /**
       * Alternative text, HTML alt tag (important for SEO)
       */
      alt?: string;
    };
  }[];
  /**
   * List of product categories
   *
   * @maxItems 100
   */
  categories?: {
    /**
     * Category ID (ObjectID)
     */
    _id?: string & { length: 24 };
    /**
     * Category name
     */
    name: string;
    /**
     * Text translations for internationalization
     */
    i18n?: {
      /**
       * Language specific text fields
       *
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^[a-z]{2}(_[a-z]{2})?$".
       */
      [k: string]: {
        /**
         * Category name
         */
        name?: string;
      };
    };
    /**
     * Category page slug
     */
    slug?: string;
    /**
     * Parent category (above) of current category
     */
    parent?: {
      /**
       * Parent category ID (ObjectID)
       */
      _id?: string & { length: 24 };
      /**
       * Parent category name
       */
      name: string;
      /**
       * Text translations for internationalization
       */
      i18n?: {
        /**
         * Language specific text fields
         *
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^[a-z]{2}(_[a-z]{2})?$".
         */
        [k: string]: {
          /**
           * Parent category name
           */
          name?: string;
        };
      };
      /**
       * Parent category page slug
       */
      slug?: string;
    };
    /**
     * Mercado Libre Taxonomy: https://api.mercadolibre.com/sites/MLB/categories
     */
    ml_category_id?: string;
    /**
     * Google Taxonomy: https://www.google.com/basepages/producttype/taxonomy-with-ids.pt-BR.txt
     */
    google_product_category_id?: number;
  }[];
  /**
   * Product's preferred category tree, separating by >, such as "Women > Dresses"
   */
  category_tree?: string;
  /**
   * Preferred category of the product in the Mercado Libre Taxonomy
   */
  ml_category_id?: string;
  /**
   * Preferred category of the product in the Google Products Taxonomy
   */
  google_product_category_id?: number;
  /**
   * Grids for specifications and variations
   *
   * @maxItems 200
   */
  grids?: {
    /**
     * Grid ID (ObjectID)
     */
    _id?: string & { length: 24 };
    /**
     * Grid title
     */
    title: string;
    /**
     * Text translations for internationalization
     */
    i18n?: {
      /**
       * Language specific text fields
       *
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^[a-z]{2}(_[a-z]{2})?$".
       */
      [k: string]: {
        /**
         * Grid title
         */
        title?: string;
      };
    };
    /**
     * Optional grid identifier for integrations, generally the grid name normalized
     */
    grid_id?: string;
  }[];
  /**
   * Product attributes and technical specifications
   */
  specifications?: {
    /**
     * Attribute to tell users the energy efficiency class of your product
     *
     * @maxItems 1
     */
    energy_efficiency_class?: {
      /**
       * Text displayed for the client describing the specification (custom value)
       */
      text: string;
      /**
       * Text translations for internationalization
       */
      i18n?: {
        /**
         * Language specific text fields
         *
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^[a-z]{2}(_[a-z]{2})?$".
         */
        [k: string]: {
          /**
           * Text displayed for the client describing the specification (custom value)
           */
          text?: string;
        };
      };
      /**
       * Value in the Google Product Specification
       */
      value?: 'A+++' | 'A++' | 'A+' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G';
      [k: string]: unknown;
    }[];
    /**
     * Attribute to set the demographic that your product is designed for
     *
     * @maxItems 1
     */
    age_group?: {
      /**
       * Text displayed for the client describing the specification (custom value)
       */
      text: string;
      /**
       * Text translations for internationalization
       */
      i18n?: {
        /**
         * Language specific text fields
         *
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^[a-z]{2}(_[a-z]{2})?$".
         */
        [k: string]: {
          /**
           * Text displayed for the client describing the specification (custom value)
           */
          text?: string;
        };
      };
      /**
       * Value in the Google Product Specification
       */
      value?: 'newborn' | 'infant' | 'toddler' | 'kids' | 'adult';
      [k: string]: unknown;
    }[];
    /**
     * Specify for what gender your product is designed
     *
     * @maxItems 1
     */
    gender?: {
      /**
       * Text displayed for the client describing the specification (custom value)
       */
      text: string;
      /**
       * Text translations for internationalization
       */
      i18n?: {
        /**
         * Language specific text fields
         *
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^[a-z]{2}(_[a-z]{2})?$".
         */
        [k: string]: {
          /**
           * Text displayed for the client describing the specification (custom value)
           */
          text?: string;
        };
      };
      /**
       * Value in the Google Product Specification
       */
      value?: 'male' | 'female' | 'unisex';
      [k: string]: unknown;
    }[];
    /**
     * Attribute to describe the main fabric or material that your product is made of
     *
     * @maxItems 1
     */
    material?: {
      /**
       * Text displayed for the client describing the attribute
       */
      text: string;
      /**
       * Text translations for internationalization
       */
      i18n?: {
        /**
         * Language specific text fields
         *
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^[a-z]{2}(_[a-z]{2})?$".
         */
        [k: string]: {
          /**
           * Text displayed for the client describing the attribute
           */
          text?: string;
        };
      };
      /**
       * Default normalized value to use on GMC and other integrations
       */
      value?: string;
      [k: string]: unknown;
    }[];
    /**
     * Attribute to describe the pattern or graphic printed on your product
     *
     * @maxItems 1
     */
    pattern?: {
      /**
       * Text displayed for the client describing the attribute
       */
      text: string;
      /**
       * Text translations for internationalization
       */
      i18n?: {
        /**
         * Language specific text fields
         *
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^[a-z]{2}(_[a-z]{2})?$".
         */
        [k: string]: {
          /**
           * Text displayed for the client describing the attribute
           */
          text?: string;
        };
      };
      /**
       * Default normalized value to use on GMC and other integrations
       */
      value?: string;
      [k: string]: unknown;
    }[];
    /**
     * Attribute to describe the standardized size of your product
     *
     * @maxItems 1
     */
    size?: {
      /**
       * Text displayed for the client describing the attribute
       */
      text: string;
      /**
       * Text translations for internationalization
       */
      i18n?: {
        /**
         * Language specific text fields
         *
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^[a-z]{2}(_[a-z]{2})?$".
         */
        [k: string]: {
          /**
           * Text displayed for the client describing the attribute
           */
          text?: string;
        };
      };
      /**
       * Default normalized value to use on GMC and other integrations
       */
      value?: string;
      [k: string]: unknown;
    }[];
    /**
     * Attribute to describe the cut of your product
     *
     * @maxItems 1
     */
    size_type?: {
      /**
       * Text displayed for the client describing the attribute
       */
      text: string;
      /**
       * Text translations for internationalization
       */
      i18n?: {
        /**
         * Language specific text fields
         *
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^[a-z]{2}(_[a-z]{2})?$".
         */
        [k: string]: {
          /**
           * Text displayed for the client describing the attribute
           */
          text?: string;
        };
      };
      /**
       * Value in the Google Product Specification
       */
      value?: 'regular' | 'petite' | 'plus' | 'big and tall' | 'maternity';
      [k: string]: unknown;
    }[];
    /**
     * Which country's sizing system your product uses
     *
     * @maxItems 1
     */
    size_system?: {
      /**
       * Text displayed for the client describing the attribute
       */
      text: string;
      /**
       * Text translations for internationalization
       */
      i18n?: {
        /**
         * Language specific text fields
         *
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^[a-z]{2}(_[a-z]{2})?$".
         */
        [k: string]: {
          /**
           * Text displayed for the client describing the attribute
           */
          text?: string;
        };
      };
      /**
       * Value in the Google Product Specification
       */
      value?: 'AU' | 'BR' | 'CN' | 'DE' | 'EU' | 'FR' | 'IT' | 'JP' | 'MEX' | 'UK' | 'US';
      [k: string]: unknown;
    }[];
    /**
     * Product color palette, list ordered by importance, starting by main color
     */
    colors?: {
      /**
       * Color name
       */
      text: string;
      /**
       * Text translations for internationalization
       */
      i18n?: {
        /**
         * Language specific text fields
         *
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^[a-z]{2}(_[a-z]{2})?$".
         */
        [k: string]: {
          /**
           * Color name
           */
          text?: string;
        };
      };
      /**
       * RGB code with #
       */
      value?: string;
    }[];
    /**
     * Custom product attributes, grid as property name (such as 'Model' and 'Voltage')
     *
     * @minItems 1
     * @maxItems 30
     *
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^.{2,70}$".
     */
    [k: string]: {
      /**
       * Text displayed for the client describing the specification
       */
      text: string;
      /**
       * Text translations for internationalization
       */
      i18n?: {
        /**
         * Language specific text fields
         *
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^[a-z]{2}(_[a-z]{2})?$".
         */
        [k: string]: {
          /**
           * Text displayed for the client describing the specification
           */
          text?: string;
        };
      };
      /**
       * Default normalized value to use in integrations
       */
      value?: string;
      /**
       * Normalized values to use in specific integrations
       */
      external_values?: {
        /**
         * Attribute text external value
         *
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^[a-z0-9_]{2,50}$".
         */
        [k: string]: string;
      };
    }[];
  };
  /**
   * List of product images
   *
   * @maxItems 50
   */
  pictures?: {
    /**
     * Picture ID (ObjectID) [auto]
     */
    _id?: string & { length: 24 };
    /**
     * Tag to identify object, use only lowercase letters, digits and underscore
     */
    tag?: string;
    normal?: PictureSize;
    big?: PictureSize1;
    zoom?: PictureSize2;
    small?: PictureSize3;
  }[];
  /**
   * List of videos related to your product
   *
   * @maxItems 30
   */
  videos?: {
    /**
     * Video link
     */
    url: string;
    /**
     * Title describing the video
     */
    title?: string;
  }[];
  /**
   * List of product customization fields
   *
   * @maxItems 100
   */
  customizations?: (
    | {
        [k: string]: unknown;
      }
    | {
        [k: string]: unknown;
      }
  )[];
  /**
   * Product variations list
   *
   * @maxItems 3000
   */
  variations?: {
    /**
     * Variation ID (ObjectID) [auto]
     */
    _id?: string & { length: 24 };
    /**
     * Item unique reference code
     */
    sku?: string;
    /**
     * Product name for this specific variation
     */
    name?: string;
    /**
     * Text translations for internationalization
     */
    i18n?: {
      /**
       * Language specific text fields
       *
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^[a-z]{2}(_[a-z]{2})?$".
       */
      [k: string]: {
        /**
         * Product name for this specific variation
         */
        name?: string;
      };
    };
    /**
     * Global Trade Item Numbers (barcode number): UPC, EAN, JAN, ISBN, ITF-14
     */
    gtin?: string;
    /**
     * Unique code specified by manufacturer to identify the product
     */
    mpn?: string;
    /**
     * List of product NCM codes
     *
     * @maxItems 10
     */
    ncm?: string[];
    /**
     * Variation sale price, when undefined, product default price should be used
     */
    price?: number;
    /**
     * Variation original sale price, without discounts
     */
    base_price?: number;
    /**
     * Variation cost price to calculate profit
     */
    cost_price?: number;
    /**
     * Product quantity available to sell, max to put in cart
     */
    quantity?: number;
    /**
     * Minimum quantity to put in cart
     */
    min_quantity?: number;
    /**
     * Warehouses by code and respective variation stock
     */
    inventory?: {
      /**
       * Variation quantity available for sale from current warehouse
       *
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^[A-Za-z0-9-_]{2,30}$".
       */
      [k: string]: number;
    };
    /**
     * Deadline for production or handling of pre-ordered product
     */
    production_time?: {
      /**
       * Number of days to post after purchase, deadline for production or handling
       */
      days: number;
      /**
       * If the deadline is calculated in working days
       */
      working_days?: boolean;
      /**
       * If the production time is cumulative per unit
       */
      cumulative?: boolean;
      /**
       * When cumulative, increase up to this maximum in days
       */
      max_time?: number;
    };
    /**
     * Product dimensions with packaging for freight calculation
     */
    dimensions?: {
      /**
       * Package width, height and length
       *
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^width|height|length$".
       */
      [k: string]: {
        /**
         * Size in specified unit
         */
        value: number;
        /**
         * Unit of measurement
         */
        unit?: 'mm' | 'cm' | 'm' | 'ft' | 'in' | 'yd' | 'mi';
      };
    };
    /**
     * Package weight for freight calculation
     */
    weight?: {
      /**
       * Size in specified unit
       */
      value: number;
      /**
       * Unit of measurement
       */
      unit?: 'mg' | 'g' | 'kg' | 'lb' | 'oz';
    };
    /**
     * Variation attributes and technical specifications
     */
    specifications: {
      /**
       * Attribute to describe the main fabric or material that your product is made of
       *
       * @maxItems 1
       */
      material?: {
        /**
         * Text displayed for the client describing the attribute
         */
        text: string;
        /**
         * Text translations for internationalization
         */
        i18n?: {
          /**
           * Language specific text fields
           *
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[a-z]{2}(_[a-z]{2})?$".
           */
          [k: string]: {
            /**
             * Text displayed for the client describing the attribute
             */
            text?: string;
          };
        };
        /**
         * Default normalized value to use on GMC and other integrations
         */
        value?: string;
        [k: string]: unknown;
      }[];
      /**
       * Attribute to describe the pattern or graphic printed on your product
       *
       * @maxItems 1
       */
      pattern?: {
        /**
         * Text displayed for the client describing the attribute
         */
        text: string;
        /**
         * Text translations for internationalization
         */
        i18n?: {
          /**
           * Language specific text fields
           *
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[a-z]{2}(_[a-z]{2})?$".
           */
          [k: string]: {
            /**
             * Text displayed for the client describing the attribute
             */
            text?: string;
          };
        };
        /**
         * Default normalized value to use on GMC and other integrations
         */
        value?: string;
        [k: string]: unknown;
      }[];
      /**
       * Attribute to describe the standardized size of your product
       *
       * @maxItems 1
       */
      size?: {
        /**
         * Text displayed for the client describing the attribute
         */
        text: string;
        /**
         * Text translations for internationalization
         */
        i18n?: {
          /**
           * Language specific text fields
           *
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[a-z]{2}(_[a-z]{2})?$".
           */
          [k: string]: {
            /**
             * Text displayed for the client describing the attribute
             */
            text?: string;
          };
        };
        /**
         * Default normalized value to use on GMC and other integrations
         */
        value?: string;
        [k: string]: unknown;
      }[];
      /**
       * Variation color palette, list ordered by importance, starting by main color
       */
      colors?: {
        /**
         * Color name
         */
        text: string;
        /**
         * Text translations for internationalization
         */
        i18n?: {
          /**
           * Language specific text fields
           *
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[a-z]{2}(_[a-z]{2})?$".
           */
          [k: string]: {
            /**
             * Color name
             */
            text?: string;
          };
        };
        /**
         * RGB code with #
         */
        value?: string;
      }[];
      /**
       * Custom variation attributes, grid as property name (such as 'Model' and 'Voltage')
       *
       * @minItems 1
       * @maxItems 6
       *
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^.{2,70}$".
       */
      [k: string]: {
        /**
         * Text displayed for the client describing the specification
         */
        text: string;
        /**
         * Text translations for internationalization
         */
        i18n?: {
          /**
           * Language specific text fields
           *
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[a-z]{2}(_[a-z]{2})?$".
           */
          [k: string]: {
            /**
             * Text displayed for the client describing the specification
             */
            text?: string;
          };
        };
        /**
         * Default normalized value to use in integrations
         */
        value?: string;
        /**
         * Normalized values to use in specific integrations
         */
        external_values?: {
          /**
           * Attribute text external value
           *
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[a-z0-9_]{2,50}$".
           */
          [k: string]: string;
        };
      }[];
    };
    /**
     * ID of one of the preferred product picture for this variation
     */
    picture_id?: string & { length: 24 };
    /**
     * Flags to associate additional info
     *
     * @maxItems 10
     */
    flags?: string[];
  }[];
  /**
   * If this product is a kit, set its composition
   *
   * @maxItems 100
   */
  kit_composition?: {
    /**
     * Product ID (ObjectID)
     */
    _id: string & { length: 24 };
    /**
     * Product quantity
     */
    quantity?: number;
    /**
     * Label shown to customer, if you want to use a title other than the product name
     */
    label?: string;
    /**
     * Text translations for internationalization
     */
    i18n?: {
      /**
       * Language specific text fields
       *
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^[a-z]{2}(_[a-z]{2})?$".
       */
      [k: string]: {
        /**
         * Label shown to customer, if you want to use a title other than the product name
         */
        label?: string;
      };
    };
    /**
     * If this product has variations
     */
    has_variations?: boolean;
    /**
     * Optional variation ID (ObjectID) if `has_variations` is true
     */
    variation_id?: string & { length: 24 };
  }[];
  /**
   * Parent product ID, if this product is contained or represented by another
   */
  parent_item_id?: string & { length: 24 };
  /**
   * Lists of related products
   *
   * @maxItems 30
   */
  related_products?: {
    /**
     * Title describing the video
     */
    title?: string;
    /**
     * Unit of measurement
     */
    relation_type?: 'common_characteristics' | 'common_orders' | 'manual' | 'other';
    /**
     * List of products
     *
     * @maxItems 100
     */
    product_ids: Array<string & { length: 24 }>;
    /**
     * Tag to identify object, use only lowercase letters, digits and underscore
     */
    tag?: string;
  }[];
  /**
   * True when related products lists should be created and updated automatically (ML)
   */
  auto_fill_related_products?: boolean;
  /**
   * Product popularity, will be filled automatically
   */
  views?: number;
  /**
   * On how many orders this product is present, filled automatically
   */
  sales?: number;
  /**
   * Total amount earned with sales of this product, filled automatically
   */
  total_sold?: number;
  /**
   * List of product GTIN codes
   *
   * @maxItems 10
   */
  gtin?: string[];
  /**
   * List of product MPN codes
   *
   * @maxItems 10
   */
  mpn?: string[];
  /**
   * List of product NCM codes
   *
   * @maxItems 10
   */
  ncm?: string[];
  /**
   * Whether the product is sold by a third party, usual in marketplaces
   */
  seller?: {
    /**
     * Unique reference code to identify this seller
     */
    code?: string;
    /**
     * Seller name
     */
    name?: string;
    /**
     * Image link to seller's logo
     */
    logo_url?: string;
    /**
     * Short description of seller
     */
    description?: string;
  };
  /**
   * List of custom attributes
   *
   * @maxItems 100
   */
  metafields?: {
    /**
     * String to help distinguish who (or which app) created and can use the metafield
     */
    namespace?: string;
    /**
     * Field name
     */
    field?: string;
    /**
     * Custom property value
     */
    value: {
      [k: string]: unknown;
    };
  }[];
  /**
   * List of custom attributes
   *
   * @maxItems 100
   */
  hidden_metafields?: {
    /**
     * String to help distinguish who (or which app) created and can use the metafield
     */
    namespace?: string;
    /**
     * Field name
     */
    field?: string;
    /**
     * Custom property value
     */
    value: {
      [k: string]: unknown;
    };
  }[];
  /**
   * Flags to associate additional info
   *
   * @maxItems 10
   */
  flags?: string[];
  /**
   * Optional notes with additional info about this product
   */
  notes?: string;
}
/**
 * Default image size variant
 */
export interface PictureSize {
  /**
   * Image link
   */
  url: string;
  /**
   * Image size (width x height) in px, such as 100x50 (100px width, 50px height)
   */
  size?: string;
  /**
   * Alternative text, HTML alt tag (important for SEO)
   */
  alt?: string;
}
/**
 * Image big size variant
 */
export interface PictureSize1 {
  /**
   * Image link
   */
  url: string;
  /**
   * Image size (width x height) in px, such as 100x50 (100px width, 50px height)
   */
  size?: string;
  /**
   * Alternative text, HTML alt tag (important for SEO)
   */
  alt?: string;
}
/**
 * Image zoom size variant
 */
export interface PictureSize2 {
  /**
   * Image link
   */
  url: string;
  /**
   * Image size (width x height) in px, such as 100x50 (100px width, 50px height)
   */
  size?: string;
  /**
   * Alternative text, HTML alt tag (important for SEO)
   */
  alt?: string;
}
/**
 * Image small size variant
 */
export interface PictureSize3 {
  /**
   * Image link
   */
  url: string;
  /**
   * Image size (width x height) in px, such as 100x50 (100px width, 50px height)
   */
  size?: string;
  /**
   * Alternative text, HTML alt tag (important for SEO)
   */
  alt?: string;
}
