/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Searches {
  _id: string & { length: 24 };
  created_at: string;
  updated_at: string;
  store_id: number;
  term: string;
  occurrences?: number;
  hits_count?: number;
  counted_at?: string;
}
