// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ADrawer: typeof import('./lib/components/ADrawer.vue')['default']
    HeaderButtonLink: typeof import('./components/header/HeaderButtonLink.vue')['default']
    HeaderButtons: typeof import('./components/header/HeaderButtons.vue')['default']
    HeaderNav: typeof import('./components/header/HeaderNav.vue')['default']
    HeaderNavLink: typeof import('./components/header/HeaderNavLink.vue')['default']
    LoginDrawer: typeof import('./lib/components/LoginDrawer.vue')['default']
    LoginForm: typeof import('./lib/components/LoginForm.vue')['default']
    Price: typeof import('./lib/components/Price.vue')['default']
    PriceCashback: typeof import('./lib/components/Price/PriceCashback.vue')['default']
    PriceCompare: typeof import('./lib/components/Price/PriceCompare.vue')['default']
    PriceDiscountLabel: typeof import('./lib/components/Price/PriceDiscountLabel.vue')['default']
    PriceInstallments: typeof import('./lib/components/Price/PriceInstallments.vue')['default']
    PriceSale: typeof import('./lib/components/Price/PriceSale.vue')['default']
    PriceWithDiscount: typeof import('./lib/components/Price/PriceWithDiscount.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TopBar: typeof import('./components/TopBar.vue')['default']
  }
}
