name: Deploy

on:
  pull_request:
    paths:
      - "packages/**"
      - "!packages/storefront"
      - "!packages/ssr"
      - "!packages/feeds"
      - "!packages/passort"
      - "!packages/!18n"
      - "!packages/__skeleton"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/e2e-tests.yml"
      - "packages/**"
      - "!packages/storefront"
      - "!packages/ssr"
      - "!packages/feeds"
      - "!packages/passort"
      - "!packages/!18n"
      - "!packages/__skeleton"

jobs:
  setup:
    name: Tests Apps
    runs-on: ubuntu-latest
    if: |
      github.event.head_commit.message != 'Initial commit' &&
      !contains(github.event.head_commit.message, '[skip ci]')

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Store
        uses: actions/checkout@v3
        with:
          repository: ecomplus/store
          path: store

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules/**
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install pnpm
        run: |
          pnpm install

      - name: Build root
        run: pnpm build

      - name: Install firebase-tools
        run: |
          npm install -g firebase-tools

      - name: Build store and initialize emulators
        env:
          ECOM_STORE_ID: ${{ secrets.ECOM_STORE_ID }}
          ECOM_AUTHENTICATION_ID: ${{ secrets.ECOM_AUTHENTICATION_ID }}
          ECOM_API_KEY: ${{ secrets.ECOM_API_KEY }}
        run: |
          cd store
          npm run build
          npx firebase --project=ecom2-002 emulators:start --only functions &

      - name: Run tests
        run: |
          sleep 10
          cd packages/modules
          npm run test:e2e
          cd ../../
